logging:
  file: logs/mod-data-migration.log
  level:
    com:
      zaxxer:
        hikari: INFO
    org:
      folio.rest: INFO
      hibernate: INFO
      springframework:
        security: INFO
        web: INFO

server:
  port: 9003
  tomcat:
    connection-timeout: -1
    accept-count: 1000
    max-connections: 100000
    max-threads: 400

spring:
  data.rest:
    returnBodyOnCreate: true
    returnBodyOnUpdate: true
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 16
    # platform: h2
    # url: jdbc:h2:./target/mod_data_migration;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    # driverClassName: org.h2.Driver
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mod_data_migration

    username: folio_admin
    password: folio_admin
  devtools:
    add-properties: false
    restart:
      enabled: false
      exclude: target
  h2:
    console:
      enabled: false
      path: /h2console
      settings:
        web-allow-others: false
  jpa:
    # database-platform: org.folio.rest.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        # dialect: org.folio.rest.dialect.H2Dialect
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 100
          lob.non_contextual_creation: true

    generate-ddl: false
    hibernate.ddl-auto: none
    open-in-view: true
    show-sql: true

  profiles:
    active: default
  thymeleaf:
    mode: TEXT
    suffix: .sql

tenant:
  header-name: X-Okapi-Tenant
  force-tenant: false
  default-tenant: diku
  initialize-default-tenant: true
  domain-packages:
  schema-scripts:

okapi:
  url: http://localhost:9130
  credentials:
    username: diku_admin
    password: admin
  modules:
    database:
      url: jdbc:postgresql://localhost:5433/okapi_modules
      username: folio_admin
      password: folio_admin
      driver-class-name: org.postgresql.Driver

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, logfile
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    logfile:
      enabled: true
